const SQL_TYPE_MAP = {
  sqlite: {
    BigIntegerField: 'bigint',
    BigSerialField: 'bigint',
    BooleanField: 'boolean',
    DateField: 'date',
    DateTimeField: 'datetime',
    FloatField: 'real',
    IntegerField: 'integer',
    JSONField: 'json',
    NumericField: 'numeric',
    SerialField: 'integer',
    TextField: 'text',
    TimeField: 'text',
    UUIDField: 'text',
    VarcharField: 'varchar',
  },
  postgresql: {
    BigIntegerField: 'bigint',
    BigSerialField: 'bigserial',
    BooleanField: 'boolean',
    DateField: 'date',
    DateTimeField: 'timestamp',
    FloatField: 'float',
    IntegerField: 'integer',
    JSONField: 'jsonb',
    NumericField: 'numeric',
    SerialField: 'serial',
    TextField: 'text',
    TimeField: 'time',
    UUIDField: 'uuid',
    VarcharField: 'varchar',
  },
  mysql: {
    BigIntegerField: 'bigint',
    BigSerialField: 'bigint',
    BooleanField: 'tinyint',
    DateField: 'date',
    DateTimeField: 'datetime',
    FloatField: 'float',
    IntegerField: 'int',
    JSONField: 'json',
    NumericField: 'decimal',
    SerialField: 'int',
    TextField: 'text',
    TimeField: 'time',
    UUIDField: 'varchar(36)',
    VarcharField: 'varchar',
  },
} as const

const SQL_OPERATORS = {
  $eq: '=',
  $neq: '!=',
  $gt: '>',
  $gte: '>=',
  $lt: '<',
  $lte: '<=',
  $in: 'IN',
  $nin: 'NOT IN',
  $null: 'IS NULL',
  $notNull: 'IS NOT NULL',
  $like: 'LIKE',
  $notLike: 'NOT LIKE',
  $ilike: 'ILIKE',
  $notIlike: 'NOT ILIKE',
  $and: 'AND',
  $or: 'OR',
  $not: 'NOT',
} as const
